# Numpy
It works mostly with numpy array (different from python's lists)

In [3]:
import numpy as np

In [5]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [6]:
for i in a:
    print(i)

1
2
3
4


**W** numpy arrays do not have the append method

In [7]:
b = np.array(["A","B"])

The "+" does not concatenate the arrays; you can do operations with arrays
Math operations can be performed with nunmpy arrays

In [8]:
print(a + a)

[2 4 6 8]


You can not sum two arrays of different size

In [12]:
print(a*a, a/a)

(array([ 1,  4,  9, 16]), array([1, 1, 1, 1]))


## Inner product
(or dot product)
The form in which the hypothesis in linear regression will be  
module(a) * module(b) * sin($\theta$)

In [17]:
a = np.array([1,2])
b = np.array([2,1])
print(np.inner(a,b))
print(np.sum(a*b))
print(np.dot(a,b))

4
4
4


## Linear Algebra
Norm:

In [18]:
print(np.linalg.norm(a))

2.23606797749979


Assessing run time

In [21]:
from datetime import datetime
t0 = datetime.now()
## code to evaluate
t1 = datetime.now()
print(t1 - t0)

0:00:00.000139


### Dot product run time comparison

In [23]:
print(a, zip(a))

(array([1, 2]), [(1,), (2,)])


In [36]:
def pydot(a,b):
    dot = []
    for i,j in zip(a,b):
        dot.append(i*j)

    return(dot)
    
def npdot(a,b):
    return(np.inner(a,b))

t0 = datetime.now()
for i in range(0,1000000):
    pydot(a,a)
t1 = datetime.now()

print(t1 - t0)

t0 = datetime.now()
for i in range(0,1000000):
    npdot(a,a)
t1 = datetime.now()

print(t1 - t0)

0:00:01.501728
0:00:01.150615


## Random

In [32]:
import random
n = random.randint(3,4)
print(n)

3


## Pandas

### Series
They are numpy arrays, indexed
Not exactly --> you can store different data type

In [41]:
import pandas as pd

data = pd.Series([1,2,"tre",5,5])
print(data)


0      1
1      2
2    tre
3      5
4      5
dtype: object


In [49]:
data = pd.Series([1,2,3,4,5], index=["one","two","three","four","five"])
print(data)
print(data.index)
print(data.index[3])

one      1
two      2
three    3
four     4
five     5
dtype: int64
Index([u'one', u'two', u'three', u'four', u'five'], dtype='object')
four


A panda series can be built from a python dictionary  
What dict do not support and series do support  
* slices
* lot of other stuff

### DataFrame
A Serie in two dimension

In [51]:
print("look at the example, you lazy ass")

look at the example, you lazy ass


## Matplotlib

## Seaborn